### ISSUE TITLE
Add Firehol in the readme?

### ISSUE THREAD

**Issue by Atavic** [pyllyukko/harden.sh#14]
You could add [Firehol](https://github.com/firehol/firehol) - a FW - [here](https://github.com/pyllyukko/harden.sh#other-security-software).

It's on [SBo](https://slackbuilds.org/repository/14.2/network/firehol/).

**Comment by pyllyukko** [comment]
I like to write my ```iptables``` rules manually, so I'll leave this out for now. Also if a firewall wrapper script would be required, I think UFW might be safer bet, as it's quite widely deployed.
