### ISSUE TITLE
Cosmetic overhaul

### ISSUE THREAD

**Issue by ghost** [pyllyukko/harden.sh#5]
I'm planning to do a cosmetic overhaul, like replacing `if [...]\nthen` with `if [...]; then`, adding newlines where needed to reduce the clutter, etc. Any chance for such pull request to be merged?

**Comment by pyllyukko** [comment]
I prefer if statements on separate lines without the `; then`.

**Comment by ghost** [comment]
Seems that we have opposing views on code readability. Well then, but what about moving *_NOT_IN_USE() functions away from `harden.sh` to, say, `testing.sh` or `todo.sh`?

**Comment by pyllyukko** [comment]
> Well then, but what about moving *_NOT_IN_USE() functions away from harden.sh to, say, testing.sh or todo.sh?

I think those can be removed. They are in the git history for reference when it's time to get back at them.
